function [tree] = sci_Build_3D_Airfoil_File(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab Build_3D_Airfoil_File()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
endfunction
