function [tree] = sci_ThousandSep(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab ThousandSep()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(-1,-1)
tree.lhs(1).type=Type(String,Real)
endfunction
