function [tree] = sci_Interp_Thickness_Profile(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab Interp_Thickness_Profile()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(-1,2)
tree.lhs(1).type=Type(Cell,Unknown)
endfunction
