function [tree] = sci_Interp_Thickness_Coefs(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab Interp_Thickness_Coefs()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
endfunction
